export enum GetStartedStrings {
    Delete = "Delete",
    DeleteResourceMessage = "Are you sure you want to delete this resource?",
    DeleteResourceTitle = "Delete resource",
    LearnMore = "Learn more",
    Move = "Move",
    PropertyFromResourceLabel = "Property from resource",
    Refresh = "Refresh",
    ResourceCommand = "Command1",
    Tab1Title = "Get started with My resource.",
    Tab1Description = "Build, manage, and monitor your resources using your Portal extension.",
    Tab2Feature1Description = "\"Explore the world of cloud computing and learn what sets Azure apart\"",
    Tab2Feature1Title = "\"Get to know Azure\"",
    Tab2Feature2Description = "\"Our mission is to empower every person and organization on the planet to achieve more.\"",
    Tab2Feature2Title = "\"Empowering others\"",
    Tab2Feature3Description = "\"GitHub is a development platform inspired by the way you work. From open source to business, you can host and review code, manage projects, and build software alongside 40 million developers.\"",
    Tab2Feature3Title = "\"Built for developers\"",
    Tab2Tutorials = "Tutorials",
    TileConsistencyDescription = "Following patterns across Azure enable users to leverage a few well-known and researched design patterns throughout Azure.",
    TileConsistencyTitle = "Azure portal design patterns",
    TileMenuDescription = "Links within pages and toolbar buttons should re-use existing menu items by using the switchItem method",
    TileMenuLinkTitle = "Open Item1",
    TileMenuTitle = "Select menu item",
    TileOpenBladeTitle = "Open blade",
    TileOpenBladeDescription = "You can open extension blade and pass needed parameters to navigate no the next experience.",
    TileOpenBladeLinkTitle = "Open blade - Keys",
}
