/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 * @extension DataManagementTest
 */

// @ts-ignore TS6133
import * as alias3_1 from "../Views/ResourceKeysBlade";
import { BladeClosedHandler, BladeClosedWithDataHandler, BladeReference } from "Fx/Composition";
export interface CreateForm_dxReferenceFactory {
    /**
     * Creates a reference to the CreateForm_dx blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedWithDataHandler<any>;
    }): BladeReference<void>;
}
export interface DataTest1_ReactViewReferenceFactory {
    /**
     * Creates a reference to the DataTest1.ReactView blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<void>;
}
export interface DataTest2_ReactViewReferenceFactory {
    /**
     * Creates a reference to the DataTest2.ReactView blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<void>;
}
export interface DataTest3_ReactViewReferenceFactory {
    /**
     * Creates a reference to the DataTest3.ReactView blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<void>;
}
export interface DataTest4_ReactViewReferenceFactory {
    /**
     * Creates a reference to the DataTest4.ReactView blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<void>;
}
export interface GetStartedOverviewWithEssentials_dxInputs {
    id: any;
}
export interface GetStartedOverviewWithEssentials_dxReferenceFactory {
    /**
     * Creates a reference to the GetStartedOverviewWithEssentials_dx blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options: {
        /** Input parameters to pass to the child blade. */
        parameters: GetStartedOverviewWithEssentials_dxInputs;
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedWithDataHandler<any>;
    }): BladeReference<GetStartedOverviewWithEssentials_dxInputs>;
}
export interface HelloWorld_ReactViewReferenceFactory {
    /**
     * Creates a reference to the HelloWorld.ReactView blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options?: {
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<void>;
}
export interface ResourceKeysBladeReferenceFactory {
    /**
     * Creates a reference to the ResourceKeysBlade blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options: {
        /** Input parameters to pass to the child blade. */
        parameters: alias3_1.ResourceKeysBladeParameters;
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedHandler;
    }): BladeReference<alias3_1.ResourceKeysBladeParameters>;
}
declare global {
    interface BladeReferenceFactories {
        "CreateForm_dx": CreateForm_dxReferenceFactory;
        "DataTest1.ReactView": DataTest1_ReactViewReferenceFactory;
        "DataTest2.ReactView": DataTest2_ReactViewReferenceFactory;
        "DataTest3.ReactView": DataTest3_ReactViewReferenceFactory;
        "DataTest4.ReactView": DataTest4_ReactViewReferenceFactory;
        "GetStartedOverviewWithEssentials_dx": GetStartedOverviewWithEssentials_dxReferenceFactory;
        "HelloWorld.ReactView": HelloWorld_ReactViewReferenceFactory;
        "ResourceKeysBlade": ResourceKeysBladeReferenceFactory;
    }
    interface MenuBladeReferenceFactories {
    }
}
