/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 */

export = ExtensionDefinition;
module ExtensionDefinition {
    export module External {
        export module Microsoft_Azure_AD {
            export const enum BladeNames {
                SelectMember = "SelectMember",
                SelectMemberV3 = "SelectMemberV3",
                RolesListBlade = "RolesListBlade",
                UserAssignmentsBlade = "UserAssignmentsBlade",
            }
            export module Blades {
                export module SelectMember {
                    export const enum Inputs {
                        collectorBindingInternals_inputs = "collectorBindingInternals-inputs",
                        collectorBindingInternals_errors = "collectorBindingInternals-errors",
                        stepInput = "stepInput",
                    }
                    export const enum Outputs {
                        collectorBindingInternals_outputs = "collectorBindingInternals-outputs",
                        collectorBindingInternals_commit = "collectorBindingInternals-commit",
                        stepOutput = "stepOutput",
                    }
                }
                export module SelectMemberV3 {
                    export const enum Inputs {
                        title = "title",
                        subtitle = "subtitle",
                    }
                    export const enum Outputs {
                    }
                }
                export module RolesListBlade {
                    export const enum Inputs {
                        scope = "scope",
                    }
                    export const enum Outputs {
                    }
                }
                export module UserAssignmentsBlade {
                    export const enum Inputs {
                        scope = "scope",
                    }
                    export const enum Outputs {
                    }
                }
            }
        }
        export module HubsExtension {
            export const enum BladeNames {
                ARGBrowseAllInMenu = "ARGBrowseAllInMenu",
                ARGBrowseResourceGroupsInMenu = "ARGBrowseResourceGroupsInMenu",
                ARGBrowseResourcesInMenu = "ARGBrowseResourcesInMenu",
                ArgEditPinnedQueryBlade = "ArgEditPinnedQueryBlade",
                ArgQueryBlade = "ArgQueryBlade",
                BrowseAll = "BrowseAll",
                BrowseAllLegacy = "BrowseAllLegacy",
                BrowseQuery = "BrowseQuery",
                BrowseResource = "BrowseResource",
                BrowseResourceGroups = "BrowseResourceGroups",
                BrowseResourcesWithTag = "BrowseResourcesWithTag",
                ResourceGroupOverview = "ResourceGroupOverview",
                ResourcePicker = "ResourcePicker",
                ResourceProperties = "ResourceProperties",
                TemplateEditorBladeV2 = "TemplateEditorBladeV2",
                GptGeneratorBlade = "GptGeneratorBlade",
                InProductFeedbackBlade = "InProductFeedbackBlade",
                DeploymentDetailsBlade = "DeploymentDetailsBlade",
                ResourceGroupMapBlade = "ResourceGroupMapBlade",
                ResourceTagsBlade = "ResourceTagsBlade",
                TagsBlade = "TagsBlade",
                AssignTagsBlade = "AssignTagsBlade",
                EditTagsBlade = "EditTagsBlade",
                BrowseFallback_ReactView = "BrowseFallback.ReactView",
                ColumnChooser_ReactView = "ColumnChooser.ReactView",
                DeploymentsList_ReactView = "DeploymentsList.ReactView",
                MoveResources_ReactView = "MoveResources.ReactView",
                MyAccess_ReactView = "MyAccess.ReactView",
                RecentResources_ReactView = "RecentResources.ReactView",
                ResourcesWithTag_ReactView = "ResourcesWithTag.ReactView",
                Tags_ReactView = "Tags.ReactView",
                UnauthorizedAssetBlade = "UnauthorizedAssetBlade",
                NotFoundAssetBlade = "NotFoundAssetBlade",
                UnavailableAssetBlade = "UnavailableAssetBlade",
                Resources = "Resources",
                BrowseAllResourcesBlade = "BrowseAllResourcesBlade",
                BrowseAllInMenu = "BrowseAllInMenu",
                BrowseResourceBlade = "BrowseResourceBlade",
                BrowseInMenu = "BrowseInMenu",
                BrowseInstanceLinkBlade = "BrowseInstanceLinkBlade",
                BrowseResourceGroupBlade = "BrowseResourceGroupBlade",
                BrowseGroupsInMenu = "BrowseGroupsInMenu",
                MapResourceGroupBlade = "MapResourceGroupBlade",
                DeployToAzure = "DeployToAzure",
                DeployFromTemplateBlade = "DeployFromTemplateBlade",
                ParametersEditorBlade = "ParametersEditorBlade",
                ParametersFileEditorBlade = "ParametersFileEditorBlade",
                TemplateEditorBlade = "TemplateEditorBlade",
                DeploymentInputsBlade = "DeploymentInputsBlade",
                DeploymentOutputsBlade = "DeploymentOutputsBlade",
                ResourceMenuBlade = "ResourceMenuBlade",
            }
            export module Blades {
                export module ARGBrowseAllInMenu {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ARGBrowseResourceGroupsInMenu {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ARGBrowseResourcesInMenu {
                    export const enum Inputs {
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module ArgEditPinnedQueryBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ArgQueryBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseAll {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseAllLegacy {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseQuery {
                    export const enum Inputs {
                        query = "query",
                        title = "title",
                        supportsEdgeZone = "supportsEdgeZone",
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseResource {
                    export const enum Inputs {
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseResourceGroups {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseResourcesWithTag {
                    export const enum Inputs {
                        tagName = "tagName",
                        tagValue = "tagValue",
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourceGroupOverview {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourcePicker {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourceProperties {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module TemplateEditorBladeV2 {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module GptGeneratorBlade {
                    export const enum Inputs {
                        title = "title",
                        subtitle = "subtitle",
                        infoBoxMessage = "infoBoxMessage",
                        placeholderText = "placeholderText",
                        generateButtonText = "generateButtonText",
                        actionButtonText = "actionButtonText",
                        apiAction = "apiAction",
                    }
                    export const enum Outputs {
                    }
                }
                export module InProductFeedbackBlade {
                    export const enum Inputs {
                        bladeName = "bladeName",
                        cesQuestion = "cesQuestion",
                        cvaQuestion = "cvaQuestion",
                        extensionName = "extensionName",
                        featureName = "featureName",
                        surveyId = "surveyId",
                    }
                    export const enum Outputs {
                    }
                }
                export module DeploymentDetailsBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourceGroupMapBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourceTagsBlade {
                    export const enum Inputs {
                        resourceId = "resourceId",
                    }
                    export const enum Outputs {
                    }
                }
                export module TagsBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module AssignTagsBlade {
                    export const enum Inputs {
                        resources = "resources",
                    }
                    export const enum Outputs {
                    }
                }
                export module EditTagsBlade {
                    export const enum Inputs {
                        resource = "resource",
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseFallback.ReactView {
                    export const enum Inputs {
                        browsePrereqsRequest = "browsePrereqsRequest",
                        isAllResources = "isAllResources",
                        isFallbackScenario = "isFallbackScenario",
                        isResourceGroups = "isResourceGroups",
                        resourceTypes = "resourceTypes",
                        scope = "scope",
                        titlePrefix = "titlePrefix",
                    }
                    export const enum Outputs {
                    }
                }
                export module ColumnChooser.ReactView {
                    export const enum Inputs {
                        subscriptions = "subscriptions",
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module DeploymentsList.ReactView {
                    export const enum Inputs {
                        resourceGroup = "resourceGroup",
                    }
                    export const enum Outputs {
                    }
                }
                export module MoveResources.ReactView {
                    export const enum Inputs {
                        resourceId = "resourceId",
                        moveType = "moveType",
                        resourceIds = "resourceIds",
                    }
                    export const enum Outputs {
                    }
                }
                export module MyAccess.ReactView {
                    export const enum Inputs {
                        resourceId = "resourceId",
                    }
                    export const enum Outputs {
                    }
                }
                export module RecentResources.ReactView {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourcesWithTag.ReactView {
                    export const enum Inputs {
                        tagName = "tagName",
                        tagValue = "tagValue",
                    }
                    export const enum Outputs {
                    }
                }
                export module Tags.ReactView {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module UnauthorizedAssetBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module NotFoundAssetBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module UnavailableAssetBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module Resources {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseAllResourcesBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseAllInMenu {
                    export const enum Inputs {
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseResourceBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseInMenu {
                    export const enum Inputs {
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseInstanceLinkBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseResourceGroupBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module BrowseGroupsInMenu {
                    export const enum Inputs {
                        resourceType = "resourceType",
                    }
                    export const enum Outputs {
                    }
                }
                export module MapResourceGroupBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module DeployToAzure {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module DeployFromTemplateBlade {
                    export const enum Inputs {
                        internal_bladeCallerParams = "internal_bladeCallerParams",
                    }
                    export const enum Outputs {
                    }
                }
                export module ParametersEditorBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module ParametersFileEditorBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module TemplateEditorBlade {
                    export const enum Inputs {
                    }
                    export const enum Outputs {
                    }
                }
                export module DeploymentInputsBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module DeploymentOutputsBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
                export module ResourceMenuBlade {
                    export const enum Inputs {
                        id = "id",
                    }
                    export const enum Outputs {
                    }
                }
            }
        }
    }
    export module AssetTypes {
    }
    export const enum AssetTypeNames {
        myResource = "MyResource",
    }
    export const enum ExtensionNames {
        DataManagementTest = "DataManagementTest",
        HubsExtension = "HubsExtension",
        Microsoft_Azure_AD = "Microsoft_Azure_AD",
    }
    export const enum BladeNames {
        createForm_dx = "CreateForm_dx",
        getStartedOverviewWithEssentials_dx = "GetStartedOverviewWithEssentials_dx",
        resourceKeysBlade = "ResourceKeysBlade",
        dataTest1_ReactView = "DataTest1.ReactView",
        dataTest2_ReactView = "DataTest2.ReactView",
        dataTest3_ReactView = "DataTest3.ReactView",
        dataTest4_ReactView = "DataTest4.ReactView",
        helloWorld_ReactView = "HelloWorld.ReactView",
    }
    export const enum CommandGroupNames {
    }
    export const enum EventTypes {
    }
    export module NotificationDefinitions {
    }
    export module ViewModels {
        export module NoModel {
            export module ResourceKeysBlade {
                export interface InputsContract {
                    id: any;
                }
                export interface SettingsContract {
                }
                export interface Contract extends MsPortalFx.ViewModels.BladeContract {
                    onInputsSet(inputs: InputsContract, settings: SettingsContract): Promise<any>;
                    commandBar: MsPortalFx.ViewModels.Toolbars.ToolbarContract;
                }
            }
        }
    }
}
