/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 * @extension DataManagementTest
 */

// @ts-ignore TS6133
import * as DashboardFilters from "Fx/Composition/DashboardFilters";
// @ts-ignore TS6133
import PartSize = MsPortalFx.Parts.PartSize;
