/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 */

export = ExtensionDefinition;
module ExtensionDefinition {
    /**
     * This is the SDK version that the extension is compiled with.
     * If there is a build break on this line then ensure that the version of the MsPortalFx.d.ts file in use came from the same currently installed SDK package version.
     */
    export const sdkMsPortalFxVersion: "12.3.0.1" = MsPortalFx.Version.current;
}
