/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 * @extension DataManagementTest
 */

import { BladeClosedWithDataHandler, BladeReference } from "Fx/Composition";
export interface GetStartedOverviewWithEssentials_dxInputs {
    id: any;
}
export interface GetStartedOverviewWithEssentials_dxReferenceFactory {
    /**
     * Creates a reference to the GetStartedOverviewWithEssentials_dx blade in the DataManagementTest extension.
     * @param options Configures the blade reference.
     */
    createReference(options: {
        /** Input parameters to pass to the child blade. */
        parameters: GetStartedOverviewWithEssentials_dxInputs;
        /** Optional callback that is invoked when the blade is closed. */
        onClosed?: BladeClosedWithDataHandler<any>;
    }): BladeReference<GetStartedOverviewWithEssentials_dxInputs>;
}
declare global {
    interface ImportedBladeReferenceFactories {
        "DataManagementTest": {
            "Blades": {
                "GetStartedOverviewWithEssentials_dx": GetStartedOverviewWithEssentials_dxReferenceFactory;
            };
            "MenuBlades": {
            };
        };
    }
}
