/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 */
/// <amd-bundling root="true" priority="1000" />

export let blade: MsPortalFx.Extension.BladeDefinition = {
    "name": "GetStartedOverviewWithEssentials_dx",
    "inputs": [
        "id"
    ],
    "templateKeyInputs": [
        "id"
    ],
    "lenses": [],
    "attributes": 0
};
