/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 */
/// <amd-dependency path="../../Views/ResourceKeysBlade" />
/// <amd-bundling root="true" priority="1000" />

export let blade: MsPortalFx.Extension.BladeDefinition = {
    "name": "ResourceKeysBlade",
    "viewModelLocator": {
        "name": "ResourceKeysBlade",
        "module": "Views/ResourceKeysBlade",
        "export": "ResourceKeysBlade"
    },
    "inputs": [
        "id"
    ],
    "viewModelName": "ResourceKeysBlade",
    "lenses": [],
    "pinnable": false,
    "initialDisplayState": 2,
    "toolbar": {
        "source": {
            "valuesFrom": [
                {
                    "referenceType": 0,
                    "property": "content.commandBar"
                }
            ]
        }
    },
    "templateBlade": {
        "partSize": 0,
        "htmlTemplateInline": {
            "file": "Client\\_generated\\NoModel.pdl",
            "content": "<div class='msportalfx-docking'><div class='msportalfx-docking-body msportalfx-padding'><div class='msportalfx-form' data-bind='pcControl: section'></div></div></div>"
        },
        "styleSheets": [],
        "isV2": true
    },
    "attributes": 1
};
