/**
 * @file Source code generated by PDL compiler.
 * @sdkversion 12.3.0.1
 * @extension HubsExtension
 */
/// <reference path="../../_extensions/Hubs/SharedTypes.d.ts" />
/// <reference path="../../_extensions/Hubs/HubsExtension.d.ts" />

import { PartReference } from "Fx/Composition";
// @ts-ignore TS6133
import * as DashboardFilters from "Fx/Composition/DashboardFilters";
// @ts-ignore TS6133
import PartSize = MsPortalFx.Parts.PartSize;
export module DeprecatedExtensionPartReference {
    export interface Options {
        filters?: { [filterId: string]: DashboardFilters.AnyFilterModel; };
    }
}
export interface DeprecatedExtensionPartReferenceFactory {
    /**
     * Creates a reference to the DeprecatedExtensionPart part in the HubsExtension extension.
     * @param options Configures the part reference.
     */
    createReference(options?: {
        /** Options to configure the part. */
        options?: DeprecatedExtensionPartReference.Options;
    }): PartReference<void>;
}
export module MonitorChartPartReference {
    export const enum Size {
        Wide = PartSize.Wide,
        Tall = PartSize.Tall,
        Large = PartSize.Large,
        HeroWide = PartSize.HeroWide,
        HeroTall = PartSize.HeroTall,
    }
    export interface Options {
        initialSize?: MonitorChartPartReference.Size;
        filters?: { [filterId: string]: DashboardFilters.AnyFilterModel; };
    }
}
export interface MonitorChartPartReferenceFactory {
    /**
     * Creates a reference to the MonitorChartPart part in the HubsExtension extension.
     * @param options Configures the part reference.
     */
    createReference(options: {
        /** Input parameters to pass to the part. */
        parameters: HubsExtension.MonitorChartPart.Parameters;
        /** Options to configure the part. */
        options?: MonitorChartPartReference.Options;
    }): PartReference<HubsExtension.MonitorChartPart.Parameters>;
}
export interface ResourcePartReferenceFactory {
    /**
     * Creates a reference to the ResourcePart part in the HubsExtension extension.
     * @param options Configures the part reference.
     */
    createReference(options: {
        /** Input parameters to pass to the part. */
        parameters: { id: string };
    }): PartReference<{ id: string }>;
}
export module ResourceTagsTileReference {
    export const enum Size {
        Small = PartSize.Small,
        Normal = PartSize.Normal,
        Wide = PartSize.Wide,
        Large = PartSize.Large,
        HeroWide = PartSize.HeroWide,
        HeroTall = PartSize.HeroTall,
        Hero = PartSize.Hero,
    }
    export interface Options {
        initialSize?: ResourceTagsTileReference.Size;
        filters?: { [filterId: string]: DashboardFilters.AnyFilterModel; };
    }
}
export interface ResourceTagsTileReferenceFactory {
    /**
     * Creates a reference to the ResourceTagsTile part in the HubsExtension extension.
     * @param options Configures the part reference.
     */
    createReference(options: {
        /** Input parameters to pass to the part. */
        parameters: HubsExtension.ResourceTagsBlade.Parameters;
        /** Options to configure the part. */
        options?: ResourceTagsTileReference.Options;
    }): PartReference<HubsExtension.ResourceTagsBlade.Parameters>;
}
export module TagsTileReference {
    export const enum Size {
        Small = PartSize.Small,
        Normal = PartSize.Normal,
        Wide = PartSize.Wide,
        Large = PartSize.Large,
        HeroWide = PartSize.HeroWide,
        HeroTall = PartSize.HeroTall,
        Hero = PartSize.Hero,
    }
    export interface Options {
        initialSize?: TagsTileReference.Size;
        filters?: { [filterId: string]: DashboardFilters.AnyFilterModel; };
    }
}
export interface TagsTileReferenceFactory {
    /**
     * Creates a reference to the TagsTile part in the HubsExtension extension.
     * @param options Configures the part reference.
     */
    createReference(options: {
        /** Input parameters to pass to the part. */
        parameters: HubsExtension.TagsBlade.Parameters;
        /** Options to configure the part. */
        options?: TagsTileReference.Options;
    }): PartReference<HubsExtension.TagsBlade.Parameters>;
}
declare global {
    interface ImportedPartReferenceFactories {
        "HubsExtension": {
            "DeprecatedExtensionPart": DeprecatedExtensionPartReferenceFactory;
            "MonitorChartPart": MonitorChartPartReferenceFactory;
            "ResourcePart": ResourcePartReferenceFactory;
            "ResourceTagsTile": ResourceTagsTileReferenceFactory;
            "TagsTile": TagsTileReferenceFactory;
        };
    }
}
